### PR TITLE
Latest changes

### PR DESCRIPTION
**Pull request by pashinov**

### CODE REVIEW

**Comment by TamtamHero** [comment]
Hello ! Could you please grant us edit rights on this PR ?
Thanks !

**Comment by pashinov** [comment]
Hi @TamtamHero ! Can you tell me how to do that?

**Comment by TamtamHero** [comment]
Hi @pashinov, it should be available on this page: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by pashinov** [comment]
Hi @TamtamHero! Probably this option is allow to owner of this fork since me, as a creator of PR, and also admin of this repo don’t see this settings option `Allow edits from maintainers`. Thomas Julien asked me to grant a write rights on this repo and I sent you invitation (https://github.com/broxus/ledger-app-freeton/invitations). You can accept and make required changes.

**Comment by TamtamHero** [comment]
Hmm the invite has expired, sorry
Can you just bump the version to 1.0.1 in the Makefile ? That's all I wanted to do before deploying it :')

**Comment by pashinov** [comment]
Hi @TamtamHero! I've bumped version to 1.0.1. You can merge :)

**Pull request merged**
